.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PAPS 1 "October 12, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
paps \- text to PostScript converter using Pango

.SH SYNOPSIS
.B paps
.RI [ options ] " files" ...

.SH DESCRIPTION
.B paps
reads an input file and writes a PostScript language or user specified
format rendering of the file to standard output. paps accepts international
text in any locale and provides internationalized text layout including text
shaping and bidirectional text rendering.
.P
If no filename argument is provided, paps reads the standard input. If the
standard input is a terminal, input is terminated by an EOF signal, usually
Control-d.

.SH OPTIONS
.B paps
follows the usual GNU command line syntax, with long options
starting with two dashes (`-'). A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-landscape
Landscape output. Default is portrait.
.TP
.B \-\-columns=cl
Format output into \fIcl\fR columns. Default is 1.
.br
Please notice this option isn't related to the terminal length as in a "80 columns terminal".
.TP
.B \-\-font=desc
Use font based on description \fIdesc\fR. Default is \fB"Monospace 12"\fR.
The format of the string representation is:
.IP
"[family-list] [style-options] [size]"
.IP
where \fIfamily-list\fR is a comma separated list of families optionally
terminated by a comma, \fIstyle-options\fR is a whitespace separated list of
words where each \fIword\fR describes one of style, variant, weight, or
stretch, and \fIsize\fR is a decimal number for size in points, e.g. "Courier,Monospace Bold Italic 10".
.TP
.B \-o, \-\-output=file
Output file. Default is \fBstdout\fR. Output format is set based on
\fIfile\fR's extension when \-\-format is not provided.
.TP
.B \-\-rtl
Do right-to-left (RTL) text layout and align text to the right. Text direction is
detected automatically. Use this option for explicit RTL layout and right
alignment.
.TP
.B \-\-justify
Justify the layout. Stretch complete lines to fill the entire width.
.TP
.B \-\-wrap=wm
Use line wrapping mode \fIwm\fR. Default is \fBword\-char\fR.
.IP
.sp
.ne 2
.mk
.na
\fBword\fR
.ad
.RS 18n
.rt
Wrap lines at word boundaries
.RE
.IP
.sp
.ne 3
.mk
.na
\fBchar\fR
.ad
.RS 18n
.rt
Wrap lines at character boundaries
.RE
.IP
.sp
.ne 3
.mk
.na
\fBword-char\fR
.ad
.RS 18n
.rt
Wrap lines at word boundaries, but fall back to character boundaries if there
is not enough space for a full word
.RE
.TP
.B \-\-show\-wrap
Mark wrapped lines with special characters.
.TP
.B \-\-paper=ps
Choose paper size. Accepted paper sizes are 'legal', 'letter', 'A3' and 'A4'.
Default is \fBA4\fR.
.TP
.B \-\-gravity=gr
Set base glyph orientation. Default is \fBauto\fR.
.IP
.sp
.ne 3
.mk
.na
\fBsouth\fR
.ad
.RS 18n
.rt
Glyphs stand upright
.RE
.IP
.sp
.ne 3
.mk
.na
\fBeast\fR
.ad
.RS 18n
.rt
Glyphs are rotated 90 degrees clockwise
.RE
.IP
.sp
.ne 3
.mk
.na
\fBnorth\fR
.ad
.RS 18n
.rt
Glyphs are upside-down
.RE
.IP
.sp
.ne 3
.mk
.na
\fBwest\fR
.ad
.RS 18n
.rt
Glyphs are rotated 90 degrees counter-clockwise
.RE
.IP
.sp
.ne 3
.mk
.na
\fBauto\fR
.ad
.RS 18n
.rt
Gravity is resolved from the context
.RE

.TP
.B \-\-gravity-hint=gh
Set how horizontal scripts behave in a vertical context. Default is
\fBnatural\fR.
.IP
.sp
.ne 3
.mk
.na
\fBnatural\fR
.ad
.RS 18n
.rt
Scripts will take their natural gravity based on the base gravity
and the script
.RE
.IP
.sp
.ne 3
.mk
.na
\fBstrong\fR
.ad
.RS 18n
.rt
Always use the base gravity, regardless of the script
.RE
.IP
.sp
.ne 3
.mk
.na
\fBline\fR
.ad
.RS 18n
.rt
For scripts not in their natural direction (e.g. Latin in East gravity), choose
per-script gravity such that every script respects the line progression. This
means, Latin and Arabic will take opposite gravities and both flow
top-to-bottom for example.
.RE
.TP
.B \-\-format=fmt
Choose output format. Default is \fBps\fR.
.IP
.sp
.ne 2
.mk
.na
\fBps\fR
.ad
.RS 18n
.rt
PostScript
.RE
.IP
.sp
.ne 2
.mk
.na
\fBpdf\fR
.ad
.RS 18n
.rt
Portable Document Format
.RE
.IP
.sp
.ne 2
.mk
.na
\fBsvg\fR
.ad
.RS 18n
.rt
Scalable Vector Graphics
.RE
.TP
.B Postscript points
Each postscript point equals to 1/72 of an inch. 36 points are 1/2 of an inch.
.TP
.B \-\-bottom-margin=bm
Set bottom margin. Default is 36 postscript points.
.TP
.B \-\-top-margin=tm
Set top margin. Default is 36 postscript points.
.TP
.B \-\-left-margin=lm
Set left margin. Default is 36 postscript points.
.TP
.B \-\-right-margin=rm
Set right margin. Default is 36 postscript points.
.TP
.B \-\-gutter-width=gw
Set gutter width. Default is 40 postscript points.
.TP
.B \-\-header
Draw page header with document name, date and page number for each page. Header
is not printed by default. 
.TP
.B \-\-header-left=fmt
Sets the formatting for the left side of the header. See FORMAT for an explanation of the header and footer formatting. Default is the current localized date.
.TP
.B \-\-header-center=fmt
Sets the formatting for the center of the header. See FORMAT for an explanation of the header and footer formatting. Default is the filename.
.TP
.B \-\-header-right=fmt
Sets the formatting for the center of the header. See FORMAT for an explanation of the header and footer formatting. Default is the Page number.
.TP
.B \-\-footer
Draw page footer with document name, date and page number for each page. Footer
is not printed by default. 
.TP
.B \-\-footer-left=fmt
Sets the formatting for the left side of the footer. See FORMAT for an explanation of the footer and footer formatting. The default formatting is an empty string.
.TP
.B \-\-footer-center=fmt
Sets the formatting for the center of the footer. See FORMAT for an explanation of the footer and footer formatting. The default formatting is an empty string.
.TP
.B \-\-footer-right=fmt
Sets the formatting for the center of the footer. See FORMAT for an explanation of the footer and footer formatting. The default formatting is an empty string.
.TP
.B \-\-title="text"
Use \fItext\fR as the title string for page header. By default the input
filename or "stdin" is used.
.TP
.B \-\-markup
Interpret input as pango markup. Pango Text Attribute Markup Language allows
marking parts of the text with tags defining additional attributes such as font
face, size, weight, colors or text decoration such as underline or
strikethrough.
.TP
.B \-\-encoding=enc
Assume encoding of the input text is \fIenc\fR. By default the encoding of the
current locale is used (e.g. UTF-8).
.TP
.B \-\-lpi=lines
Set number of lines per inch. This determines the line spacing.
.TP
.B \-\-cpi=chars
Set number of characters per inch. This is an alternative method of specifying
the font size.
.TP
.B \-\-g-fatal-warnings
Make all glib warnings fatal.
.br

.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.mk
.na
\fB0\fR
.ad
.RS 6n
.rt
Successful completion.
.RE
.sp
.ne 2
.mk
.na
\fB1\fR
.ad
.RS 6n
.rt
An error occurred.
.RE

.SH HEADER AND FOOTER FORMATTING
.sp
.LP
The header and footers may be formatted by a mini language based on the python f-strings. Text outside of squiggly brackets are entered literally in the output. Text inside squiggly brackets contain one of the following predefined list of variables:

.IP
.sp
.ne 2
.mk
.na
\fBnow\fR
.ad
.RS 18n
.rt
The current time
.RE
.IP
.sp
.ne 2
.mk
.na
\fBmtime\fR
.ad
.RS 18n
.rt
The modification time of the file being printed
.RE
.IP
.sp
.ne 2
.mk
.na
\fBpage_idx\fR
.ad
.RS 18n
.rt
The page index of the page
.RE
.IP
.sp
.ne 2
.mk
.na
\fBnum_pages\fR
.ad
.RS 18n
.rt
The total number of pages in the document
.RE
.IP
.sp
.ne 2
.mk
.na
\fBfilename\fR
.ad
.RS 18n
.rt
The filename (basename) of the document
.RE
.IP
.sp
.ne 2
.mk
.na
\fBpath\fR
.ad
.RS 18n
.rt
The full path of the document
.RE

.SH EXAMPLES
.LP
\fBExample 1\fR Printing UTF-8 text file
.P
The following command can be used to print a file in any of the UTF-8 based
locales if the file is in UTF-8 or compatible codeset.
.sp
.in +2
.nf
$ \fBpaps en_US_UTF-8.txt\fR
.fi
.in -2
.LP
By default paps will print PostScript rendering to standard output. Send the
output to a printer using \fBlp\fR
.sp
.in +2
.nf
$ \fBpaps en_US_UTF-8.txt | lp\fR
.fi
.in -2
.LP
.sp
or to a file using redirection or the \fB-o\fR option
.sp
.in +2
.nf
$ \fBpaps en_US_UTF-8.txt > out.ps\fR
$ \fBpaps -o out.ps en_US_UTF-8.txt\fR
.fi
.in -2
.sp
.LP
.sp

.LP
\fBExample 2\fR Specify encoding
.P
To print a file in specific encoding regardless of the current locale setting
use the \-\-encoding option. An example for Japanese EUC encoded input file:
.sp
.in +2
.nf
$ \fBpaps --encoding eucjp ja_JP_eucjp.txt > out.ps\fR
.fi
.in -2
.LP
paps will still use current locale setting to prioritize the available fonts
for current language.

.LP
\fBExample 3\fR Specify locale
.P
Override the \fBLC_ALL\fR environment variable to run paps in a different
locale.
.sp
.in +2
.nf
$ \fBLC_ALL=ja_JP.eucjp paps ja_JP_eucjp.txt > out.ps\fR
.fi
.in -2
.LP
Here paps will assume the input is in Japanese EUC encoding and will use
Japanese eucjp locale to render the output. If \-\-header is added, the date is
printed in Japanese.

.LP
\fBExample 4\fR Change the header and footer 
.P
Override the header and the footer to show only the page in the middle of the footer.
.sp
.in +2
.nf
$ \fBpaps --separation-lines -o /tmp/foo.pdf --header --header-left='' \\
 --header-center='{path}' --header-right='' --footer \\
 --footer-left='Printed {now:%c}' \\
 --footer-right='Page {page_idx}/{num_pages}' \\
 `pwd`/paps.ccx\fR
.fi
.in -2
.LP
Here paps will assume the input is in Japanese EUC encoding and will use
Japanese eucjp locale to render the output. If \-\-header is added, the date is
printed in Japanese.

.SH ENVIRONMENT VARIABLES
.B paps
uses locale environment variables to determine its behavior. The following
categories are used:
.sp
.ne 2
.mk
.na
\fBLC_CTYPE\fR
.ad
.RS 16n
.rt
to assume the encoding of the input. This can be overridden by \-\-encoding.
.RE
.sp
.ne 2
.mk
.na
\fBLC_TIME\fR
.ad
.RS 16n
.rt
to format the date for header.
.RE

Font selection is also affected by current locale. Example 3 describes how to
run paps in a different locale.

.SH SEE ALSO
.sp
.LP
\fBfc\-match\fR(1), \fBsetlocale\fR(3C)
.sp
.LP

.SH AUTHOR
paps was written by Dov Grobgeld <dov.grobgeld@gmail.com>.
.PP
This manual page was written by Lior Kaplan <kaplan@debian.org>,
for the Debian project (but may be used by others).
