env = Environment()
env.ParseConfig('pkg-config --cflags --libs pangoft2')

env.Library('paps',
            ['libpaps.c'])

env.Program('paps',
            ['paps.c'],
            LIBPATH = ['.'],
            LIBS=['paps'] + env['LIBS'])
            
